name: Cache-Stuff
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: [update-flake-lock]
    types:
      - completed

permissions:
  contents: read

env:
  NIXOS_HOSTNAME: "Ainz-NIX"
  NIXOS_USER: "masum"
  NIXOS_ATTRS_LIST: >
    programs.hyprland.package
    programs.hyprland.portalPackage
    services.ananicy.package
    programs.appimage.package
    boot.kernelPackages.kernel
  NIXOS_PKGS_LIST: >
    zed-editor_git
    scx.full
  CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  CACHIX_CACHE_NAME: "johnrtitor"
  REQUIRED_PACKAGES: >
    cachix
    jq
    findutils

jobs:
  cache:
    name: Cache Stuff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions

      - name: setup nix
        uses: ./.github/actions/setup-nix

      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
          for PKG in $REQUIRED_PACKAGES; do
            nix profile add nixpkgs#$PKG
          done

      - name: Build Packages and push to Cachix
        run: |
          chmod +x ./.github/scripts/build-and-cache.sh
          ./.github/scripts/build-and-cache.sh
