name: update-flake-lock
on:
  workflow_dispatch:
    inputs:
      bumpWhat:
        description: Which flake input? (leave blank for all)
        required: false
        type: string

  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
    # - cron: '0 0 * * *' # runs everyday at 00:00
  push:
    paths:
      - "flake.nix"
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          inputs: ${{ inputs.bumpWhat }}
